import type { FaIconsConfig, FaPackage } from './constants.js'
import { FA_PACKAGE_MODULE, resolveIconSets, toFaExportName } from './constants.js'
import { SETUP_MODULE } from './modules.js'

export interface RdsIconsOptions {
  /**
   * Font Awesome Pro style packages to enable.
   * Only icons listed under `icons` (and the RDS preset when `rds` is true)
   * are imported from each package — nothing else is bundled.
   * @default ['light']
   */
  packages?: FaPackage[]

  /**
   * Icons to register, keyed by FA style package (kebab-case names).
   * @example { light: ['star', 'heart'], solid: ['user'] }
   */
  icons?: FaIconsConfig

  /**
   * Include all icons used by ADMS RDS UI components.
   * @default true
   */
  rds?: boolean
}

/** Generate the virtual `@banavasi/adms-rds-ui-icons/setup` module source. */
export function generateSetupModule(options: RdsIconsOptions = {}): string {
  const packages = options.packages ?? ['light']
  const rds = options.rds !== false
  const iconSets = resolveIconSets(options.icons ?? {}, { packages, rds })

  const importLines: string[] = []
  const registerNames: string[] = []

  for (const pkg of packages) {
    const names = iconSets[pkg]
    if (!names?.length) continue

    const moduleId = FA_PACKAGE_MODULE[pkg]
    // Alias each import per package so the same icon enabled in multiple
    // weights (e.g. chevron-down in light + solid) doesn't collide on one
    // local identifier (`Identifier faChevronDown has already been declared`).
    // `library.add` keys by the definition's prefix+name, so the local JS
    // identifier is irrelevant — only uniqueness matters.
    const suffix = pkg.replace(/[^a-z0-9]/gi, '_')
    const specifiers = names.map((name) => {
      const exportName = toFaExportName(name)
      return { exportName, localName: `${exportName}_${suffix}` }
    })
    importLines.push(
      `import { ${specifiers
        .map((s) => `${s.exportName} as ${s.localName}`)
        .join(', ')} } from '${moduleId}'`
    )
    registerNames.push(...specifiers.map((s) => s.localName))
  }

  const libraryAdd =
    registerNames.length > 0 ? `library.add(${registerNames.join(', ')})` : '// no icons configured'

  return `// Generated by @banavasi/adms-rds-ui-icons — do not edit.
import { config, library } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
${importLines.join('\n')}

config.autoAddCss = false
${libraryAdd}
`
}

/** Virtual app module: icon setup + global `<FontAwesomeIcon>` registration. */
export function generateAppModule(): string {
  return `// Generated by @banavasi/adms-rds-ui-icons — do not edit.
import '${SETUP_MODULE}'
import { rdsFontAwesome } from '@banavasi/adms-rds-ui-icons'

export { rdsFontAwesome }
export default rdsFontAwesome
`
}
